### ISSUE TITLE
Implement IP to Ethernet stream transformer using ARP module

### ISSUE THREAD

**Issue by rowanG077** [GiPHouse/qbaylogic-clash-based-macipudp-stack-spring24#73]
**Feature description**
Similar to https://github.com/GiPHouse/qbaylogic-clash-based-macipudp-stack-spring24/issues/72 but use a MAC address which is obtained from the ARP service instead of hardcoded MAC address.

**Expected behaviour**
The constructed `EthernetHeader` matches what is in the response from `ARPLookup`.

The circuit is expected to have type

```Haskell
toEthernetStream
  :: HiddenClockResetEnable dom
  => Signal dom MacAddress
  -- ^ My mac address
  -> Circuit (PacketStream dom n IPAddress) (PacketStream dom n EthernetHeader, ARPLookup dom)
```

**Expected steps**
Send out MAC Address lookups to the ARP service and use the given MAC to construct an `EthernetHeader` metatype so an `PacketStream dom n EthernetHeader` can be produced.

**Comment by MatthijsMu** [comment]
* will this function replace `toEthernetC`? Will it reside in  `EthernetTypes`, or `ArpTypes`, or its own file?
* Is it like `ArpManager`, where we await the result of a lookup?
* In that case, we may want to give an extra knownnat `maxWaitSeconds` like in `ArpManager`.

**Comment by t-wallet** [comment]
Yes it replaces `toEthernetC`. I would say it belongs in the IPv4 module somewhere.

No you don't have to do any timeouts here. All you have to do is keep driving the same IP address until the ARP manager acknowledges (i.e. sends `Just ArpEntryFound ...` or `Just ArpEntryNotFound`. In case of the latter you need to drop the entire packet to avoid stalling the network stack.

**Comment by rowanG077** [comment]
Yes I would say make an `IP.hs` file similar to the other protocols and put it there.
