### ISSUE TITLE
PacketBuffer drop packets which are too large

### ISSUE THREAD

**Issue by JasmijnB** [GiPHouse/qbaylogic-clash-based-macipudp-stack-spring24#82]
**Feature description**
Right now the packetBuffer will enter a deadlock if a packet longer than the maximum capacity (2^sizeBits) is loaded into it. This might cause unexpected behavior. 

**Expected behaviour**
The packetBuffer should have the option to drop packets larger than the maximum capacity.

**Expected steps**
- Create a new circuit called packetCounter. which counts a packet. If a packet is longer than a certain number, the packetCounter wil send an abort, 
- Make the packetcounter with as parameter 2^sizebits drive the packetstream and export this as a new circuit

**Additional Context**
[Any additional Context]

**Comment by rowanG077** [comment]
Fixed via https://github.com/GiPHouse/qbaylogic-clash-based-macipudp-stack-spring24/issues/57
